BEGIN;

    DROP TABLE position_report;
    DROP TABLE addressed_safety_message;
    DROP TABLE addressed_binary_message;
    DROP TABLE aids_to_navigation_report;
    DROP TABLE assigned_mode_command_commands;
    DROP TABLE base_station_report;
    DROP TABLE binary_acknowledge_destinations0;
    DROP TABLE binary_broadcast_message;
    DROP TABLE channel_management;
    DROP TABLE coordinated_utc_inquiry;
    DROP TABLE data_link_management_message_data0;
    DROP TABLE extended_class_b_position_report;
    DROP TABLE gnss_broadcast_binary_message;
    DROP TABLE group_assignment_command;
    DROP TABLE interrogation_station1_msg1;
    DROP TABLE interrogation_station1_msg2;
    DROP TABLE interrogation_station2;
    DROP TABLE long_range_ais_broadcast_message;
    DROP TABLE multi_slot_binary_message;
    DROP TABLE safety_broadcast_message;
    DROP TABLE ship_static_data;
    DROP TABLE single_slot_binary_message;
    DROP TABLE standard_class_b_position_report;
    DROP TABLE standard_search_and_rescue_aircraft_report;
    DROP TABLE static_data_report;
    DROP TABLE application_id;
    DROP TABLE assigned_mode_command;
    DROP TABLE binary_acknowledge;
    DROP TABLE addressed_binary_message_application_id;
    DROP TABLE channel_management_area;
    DROP TABLE channel_management_unicast;
    DROP TABLE data_link_management_message;
    DROP TABLE interrogation;
    DROP TABLE ship_static_data_eta;
    DROP TABLE static_data_report_report_a;
    DROP TABLE static_data_report_report_b;
    DROP TABLE ship_static_data_dimensions;

COMMIT;